package schtativ.datamanagementservice.common.sql;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.util.Assert;
import schtativ.datamanagementservice.common.StringHelper;
import schtativ.datamanagementservice.common.sql.entity.Column;
import schtativ.datamanagementservice.common.sql.entity.type.CharDataTypeInfo;
import schtativ.datamanagementservice.common.sql.entity.type.DataType;

import java.util.ArrayList;
import java.util.List;

@SpringBootTest
class SqlBuilderTest {

    @Autowired
    private SqlBuilderFactory sqlBuilderFactory;

    @Test
    void createTableBuild() {
        String standard = "CREATE TABLE data.test(id integer generated by default as identity constraint data_test_pkey primary key, code varchar(255) not null, description varchar(1024) null);";

        List<Column> columns = new ArrayList<>();
        columns.add(new Column("code", new CharDataTypeInfo(DataType.STRING, 255), false));
        columns.add(new Column("description", new CharDataTypeInfo(DataType.STRING, 1024), true));

        String sql = sqlBuilderFactory.get()
                .createTable("data", "test")
                .primaryKey(DataType.INT)
                .columns(columns)
                .build();

        Assert.isTrue(StringHelper.notEmpty(sql), "CreateTableBuild SQL Script generation is broken");
        Assert.isTrue(sql.equals(standard), "Generated query is not corrected");
    }
}